defaults:
  - callbacks: callbacks
  - scheduler: cosinewarm
  - optimizer: adamw
  - data_mode: good_quality

general:
  base_dir: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/
  logs_dir: ${general.base_dir}lightning_logs/
  seed: 13
  num_workers: 4
  gpu_list: [0, 1]

model:
  model_id: 217
  regression: false
  architecture_name: resnext50_32x4d
  dropout: 0.3
  input_size: [512, 512]
  crop_method: resize

training:
  batch_size: 32
  lr: 1e-5
  augmentations: base
  mixup: 0.
  cutmix: 0.
  label_augmentation: 0.
  max_epochs: 20
  fold: 0
  val_metric: val_rmse
  metric_mode: min
  pretrain_dir: ""

testing:
  folds: [0, 1, 2, 3, 4]
  test_csv: ${general.base_dir}data/SampleSubmission.csv
  evaluate: true
  tta: true
  pseudolabels: false

hydra:
  run:
    dir: ${general.logs_dir}model_${model.model_id}
