defaults:
  - callbacks: callbacks
  - scheduler: cosinewarm
  - optimizer: adamw
  - data_mode: good_quality

training:
  model_id: 159
  regression: false
  architecture_name: resne50
  dropout: 0.3
  input_size: 256
  crop_method: resize
  batch_size: 32
  lr: 1e-5
  augmentations: base
  max_epochs: 20
  fold: 0
  val_metric: val_rmse
  metric_mode: min
  pretrain_dir: ""
  base_dir: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/
  logs_dir: ${training.base_dir}lightning_logs/
  seed: 13
  num_workers: 4
  gpu_list: [0, 1]

testing:
  folds: [0, 1, 2, 3, 4]
  test_csv: ${training.base_dir}data/SampleSubmission.csv
  evaluate: false
  tta: true
  pseudolabels: false

hydra:
  run:
    dir: ${training.logs_dir}model_${training.model_id}
