defaults:
  - callbacks: callbacks

training:
  model_id: 12
  architecture_name: resnet34
  dropout: 0.3
  num_classes: 7
  input_size: 256
  train_batch_size: 32
  valid_batch_size: 32
  max_epochs: 30
  fold: 0
  num_workers: 4
  val_metric: val_rmse
  logs_dir: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/lightning_logs/
  lr: 3e-5
  seed: 13
  augmentations: v1
  pseudolabels: false
  pseudolabels_path: ""
  pretrain_path: ""
  train_csv: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/data/Train_proc.csv
  data_dir: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/data/Images/
  gpu_list: "0"

testing:
  checkpoint_path: /kaggle/input/twitter-roberta-base-model/
  folds: "0,1,2,3,4"

hydra:
  run:
    dir: ${training.logs_dir}/model_${training.model_id}
