defaults:
  - callbacks: callbacks
  - scheduler: cosinewarm
  - optimizer: adamw
  - data_mode: good_quality

training:
  model_id: 99
  regression: false
  architecture_name: resnet50
  dropout: 0.3
  input_size: 256
  batch_size: 32
  lr: 1e-5
  augmentations: base
  max_epochs: 20
  fold: 0
  val_metric: val_rmse
  metric_mode: min
  pretrain_dir: ""
  logs_dir: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/lightning_logs/
  seed: 13
  num_workers: 4
  gpu_list: [0, 1]

testing:
  folds: [0, 1, 2, 3, 4]
  test_csv: /data/ybabakhin/data/zindi_wheat/zindi_wheat_growth/data/SampleSubmission.csv
  evaluate: true
  tta: true
  pseudolabels: false

hydra:
  run:
    dir: ${training.logs_dir}/model_${training.model_id}
